hobby_clubs/urls.py
'''Defines URL patterns for hobby_clubs'''
from django.urls import path
from . import views
from .views import logout_view
from django.urls import re_path

from django.contrib.auth import views as auth_views

# from .views import rate_club



app_name = 'hobby_clubs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    path('search/', views.search_clubs, name='search_clubs'),

    path('logout/', logout_view, name='logout'),

    path('all-clubs/', views.all_clubs, name='all_clubs'),

    path('science-clubs/', views.science_clubs, name='science_clubs'),

    path('art-clubs/', views.art_clubs, name='art_clubs'),

    path('sports-clubs/', views.sports_clubs, name='sports_clubs'),

    path('user/profile/', views.user_profile, name='user_profile'),

    path('like-club/<str:club_name>/', views.like_club, name='like_club'),

    re_path(r'^submit_review/(?P<club_name>[\w\s\-]+)/$', views.submit_review, name='submit_review'),
]

tkc_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_accounts/', include('user_accounts.urls')),
    path('',include('hobby_clubs.urls')),
]

user_accounts/urls.py
"""Defines URL patterns for accounts."""
from django.urls import path, include
from .import views
from django.contrib.auth import views as auth_views  # Import the auth views

app_name = 'user_accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registeration page.
    path('register/', views.register, name='register'),
    # Logout page
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

hobby_clubs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg


class Club(models.Model):
    club_name = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20) 
    address = models.CharField(max_length=255)
    age = models.CharField(max_length=20)
    category = models.CharField(max_length=50)
    activity = models.CharField(max_length=100)
    website = models.URLField(max_length=200)
    # unique_identifier = models.CharField(max_length=100, unique=True)

    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.00)

    def __str__(self):
        return self.club_name

    def calculate_average_rating(self):
        """Calculate the average rating"""
        average_rating = self.ratings.aggregate(Avg('rating'))['rating__avg']
        self.average_rating = round(average_rating, 2) if average_rating else 0.00
        self.save()


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    content = models.TextField() 
    created_at = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

hobby_clubs/forms.py
from django import forms
from .models import Club, Review, Rating

class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['club_name','address','activity','website']
        labels = {'club_name':'','address':'','activity':'','website':''}

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['my_review']
        labels = {'my_review':''}
        widgets = {'my_review': forms.Textarea(attrs={'cols': 80})}


class RatingForm(forms.Form):
    rating = forms.IntegerField(label='Rating', min_value=1, max_value=5)

hobby_clubs/views.py
import csv
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Club, Like, Review
from django.http import JsonResponse
from django.shortcuts import get_object_or_404


def index(request):
    """The home page for Hobby Log."""
    return render(request, 'hobby_clubs/index.html')


@login_required
def all_clubs(request):
    clubs = Club.objects.all() 
    return render(request, 'hobby_clubs/all_clubs.html', {'clubs': clubs})


@login_required
def science_clubs(request):
    science_clubs = Club.objects.filter(category='Science')
    return render(request, 'hobby_clubs/science_clubs.html', {'science_clubs': science_clubs})

@login_required
def art_clubs(request):
    art_clubs = Club.objects.filter(category='Art')
    return render(request, 'hobby_clubs/art_clubs.html', {'art_clubs': art_clubs})

@login_required
def sports_clubs(request):
    sports_clubs = Club.objects.filter(category='Sports')
    return render(request, 'hobby_clubs/sports_clubs.html', {'sports_clubs': sports_clubs})


def search_clubs(request):
    if request.method == 'GET':
        postal_code = request.GET.get('postcode')
        age = request.GET.get('age')
        club_type = request.GET.get('clubtype')
        
        matching_clubs = []

        with open('databasestore/clubs-info.csv', 'r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            for row in reader:
                if (postal_code == row['Postal_Code'] and
                    age == row['Age'] and
                    club_type == row['Category']):
                    matching_clubs.append(row)
        if not matching_clubs:
            message = "Apologies, there are currently no clubs that match your criteria. Please try different search criteria."
            return render(request, 'hobby_clubs/search_results.html', {'message': message})
        
        return render(request, 'hobby_clubs/search_results.html', {'matching_clubs': matching_clubs})

from django.contrib.auth import logout

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        print("User loggedout")
        return redirect('hobby_clubs:index')
    return redirect('hobby_clubs:index') 
    
from django.shortcuts import render, get_object_or_404
from .models import Like, Club

@login_required
def like_club(request, club_name):
    club = get_object_or_404(Club, club_name=club_name)
    try:
        like, created = Like.objects.get_or_create(user=request.user, club=club)
        if created:
            message = 'You have successfully liked this club!'
        else:
            like.delete()
            message = 'You have successfully unliked this club!'
        return JsonResponse({'success': True, 'message': message})
    except Like.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Club not found'}, status=404)

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json

@csrf_exempt  # 如果使用 AJAX，确保处理 CSRF 问题或在前端设置正确的 CSRF token
def submit_review(request, club_name):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))  # 解析 JSON 数据
        content = data.get('content', '')
        club_name = data.get('clubName', club_name) 
        user = request.user
        club = get_object_or_404(Club, club_name=club_name)

        if not content:
            return JsonResponse({'success': False, 'error': 'Content cannot be empty'}, status=400)

        review = Review.objects.create(user=user, club=club, content=content)
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=405)


@login_required
def user_profile(request):
    liked_clubs = Like.objects.filter(user=request.user).select_related('club')
    user_reviews = Review.objects.filter(user=request.user).select_related('club')
    return render(request, 'hobby_clubs/user_profile.html', {'user': request.user, 'liked_clubs': liked_clubs, 'user_reviews': user_reviews})

hobby_clubs/templates/hobby_clubs/all_clubs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>All Clubs</title>
  <script src="{% static 'main.js' %}"></script>
  <!-- <script>
    window.csrf_token = "{{ csrf_token }}";
  </script> -->
  <style>
    body {
      font-family: 'Comic Sans MS', Tahoma, Geneva, Verdana, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #cfcede;
    }

    a {
      font-size: 18px;
      text-decoration: none;
      right: 10px;

    }

    a:hover {
      color: #d65e5e;

    }

    .front {
      color: #eabfbf;

    }

    .back {

      color: #bd4d4d;

    }

    .container {
      max-width: 900px;
      margin: auto;
      padding: 50px;
      background-color: rgba(243, 207, 229, 0.8);
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);

      background-image: url("/static/images/art.jpg");
      background-size: cover;
      background-position: top;
    }

    h1 {
      text-align: center;
      margin-bottom: 30px;
      color: #e7d9d9;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
    }

    ul {
      list-style-type: none;
      padding: 0;
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;

    }

    li {
      width: 45%;
      background-color: #d1bed1;
      border-radius: 10px;
      margin-bottom: 20px;
      padding: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      position: relative;
      transition: transform 0.3s ease;
    }

    li:hover {
      transform: translateY(-5px);
    }

    .club-name {
      font-weight: bold;
      font-size: 24px;
      color: #333;
    }

    .club-details {
      margin-top: 15px;
    }

    .club-details p {
      margin: 8px 0;
      font-size: 16px;
      color: #555;
    }

    .action-btns {
      margin-top: 20px;
    }

    .action-btn {
      margin-right: 10px;
      padding: 10px 16px;
      background-color: #d295b0;
      color: #fff;
      border: none;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s ease;
      font-size: 16px;
    }

    .action-btn:hover {
      background-color: #b07289;
    }

    .review-btns {
      margin-top: 20px;
    }

    .review-btn {
      margin-right: 10px;
      padding: 10px 16px;
      background-color: #d295b0;
      color: #fff;
      border: none;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s ease;
      font-size: 16px;
    }

    .review-btn:hover {
      background-color: #b07289;
    }

    .club-details img {
      width: 30px;
    }

    .modal {
      position: fixed;
      top: 40%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: #f9d5d5;
      padding: 20px;
      border-radius: 10px;
      z-index: 1000;

      box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
      height: 230px;
    }

    #reviewModal button {
      font-family: 'Comic Sans MS';
      width: 150px;

      font-size: 20px;
      color: #010101
    }

    .modal-content {
      max-width: 440px;
      height: 400px;
      padding-top: 20px;

      padding: 20px;

      margin: 0 auto;
      position: relative;

    }

    .modal-content h2 {
      font-size: 20px;

      margin-top: 10px;

      margin-bottom: 10px;

    }

    .close {
      position: absolute;

      top: 10px;

      right: 10px;

      font-size: 24px;

    }

    #submitReviewBtn {
      background-color: white;
      color: white;
      border: none;
      border-radius: 5px;
      padding: 5px 10px;
      font-size: 14px;
      cursor: pointer;
      bottom: 15px;
      right: 20px;
      min-width: 60px;
      min-height: 30px;
      margin-bottom: 20px;
      margin-right: 28px;

    }

    #reviewModal .modal-content button {
      float: right;
      margin-top: 10px;

    }

    #reviewTextarea {
      margin-right: 10px;
      vertical-align: top;

    }

    #reviewModal .modal-content button {
      display: inline-block;
      vertical-align: top;

    }
  </style>




</head>

<body>
  <div class="container">
    <a href="{% url 'hobby_clubs:index' %}" class="front">Back to Homepage</a>
    <h1>Discover all kids' clubs in Turku area right here!</h1>
    <ul>
      {% for club in clubs %}
      <li>
        <div class="club-name">{{ club.club_Name }}</div>
        <div class="club-details">
          <p><img src="/static/images/membership-card.png"> <strong>Club Name:</strong> {{ club.club_name }}</p>
          <p><img src="/static/images/zip-code.png"> <strong>Postal Code:</strong> {{ club.postal_code }}</p>
          <p><img src="/static/images/location-pin.png"> <strong>Address:</strong> {{ club.address }}</p>
          <p><img src="/static/images/age-group.png"> <strong>Age:</strong> {{ club.age }}</p>
          <p><img src="/static/images/categories.png"> <strong>Category:</strong> {{ club.category }}</p>
          <p><img src="/static/images/mobile.png"> <strong>Activity:</strong>{{ club.activity }}</p>
          <div class="action-btns">
            <a href="{{ club.website }}" class="action-btn" target="_blank">View Details</a>

            <button class="action-btn like-btn" data-club-name="{{ club.club_name }}">Like &#10084;</button>

            <button class="review-btn" data-club-name="{{ club.club_name }}"
              onclick="openReviewModal('{{ club.club_name }}')">Write a Review</button>


          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
    <a href="{% url 'hobby_clubs:index' %}" class="back">Back to Homepage</a>
  </div>

  <div id="reviewModal" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" onclick="closeReviewModal()">&times;</span>
      <h2>Write a Review</h2>
      <textarea id="reviewTextarea" rows="6" cols="50"></textarea>
      <input type="hidden" id="clubNameInput" value="{{ club.club_name }}">
      <button id="submitReviewBtn">Submit</button>
    </div>
  </div>


</body>

</html>

hobby_clubs/templates/hobby_clubs/art_clubs.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Art Clubs</title>
  <style>
    body {
      font-family: 'Comic Sans MS', Tahoma, Geneva, Verdana, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #cfcede;
    }

    a {
      font-size: 18px;
      text-decoration: none;
      right: 10px;
    }

    a:hover {
      color: #d65e5e;
    }

    .front {
      color: #df3c3c;

    }

    .back {

      color: #bd4d4d;

    }

    .container {
      max-width: 900px;
      margin: auto;
      padding: 50px;
      background-color: rgba(243, 207, 229, 0.8);
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
      background-image: url("/static/images/art.jpg");
      background-size: cover;
      background-position: top;
    }

    h1 {
      text-align: center;
      margin-bottom: 30px;
      color: hsl(303, 40%, 55%);
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
    }

    ul {
      list-style-type: none;
      padding: 0;
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
    }

    li {
      width: 45%;
      background-color: #d1bed1;
      border-radius: 10px;
      margin-bottom: 20px;
      padding: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      position: relative;
      transition: transform 0.3s ease;
    }

    li:hover {
      transform: translateY(-5px);
    }

    .club-name {
      font-weight: bold;
      font-size: 24px;
      color: #333;
    }

    .club-details {
      margin-top: 15px;
    }

    .club-details p {
      margin: 8px 0;
      font-size: 16px;
      color: #555;
    }

    .action-btns {
      margin-top: 20px;
    }

    .action-btn {
      margin-right: 10px;
      padding: 10px 16px;
      background-color: #d295b0;
      color: #fff;
      border: none;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s ease;
      font-size: 16px;
    }

    .action-btn:hover {
      background-color: #b07289;
    }

    .review-btns {
      margin-top: 20px;
    }

    .review-btn {
      margin-right: 10px;
      padding: 10px 16px;
      background-color: #d295b0;
      color: #fff;
      border: none;
      border-radius: 5px;
      text-decoration: none;
      cursor: pointer;
      transition: background-color 0.3s ease;
      font-size: 16px;
    }

    .review-btn:hover {
      background-color: #b07289;
    }

    .club-details img {
      width: 30px;
    }
  </style>
</head>

<body>
  <div class="container">
    <a href="{% url 'hobby_clubs:index' %}" class="front">Back to Homepage</a>
    <h1>Explore Your Artistic Side Here!</h1>
    <ul>
      {% for club in art_clubs %}
      <li>
        <div class="club-name">{{ club.club_name }}</div>
        <div class="club-details">
          <p><img src="/static/images/membership-card.png"> <strong>Club Name:</strong> {{ club.club_name }}</p>
          <p><img src="/static/images/zip-code.png"> <strong>Postal Code:</strong> {{ club.postal_code }}</p>
          <p><img src="/static/images/location-pin.png"> <strong>Address:</strong> {{ club.address }}</p>
          <p><img src="/static/images/age-group.png"> <strong>Age:</strong> {{ club.age }}</p>
          <p><img src="/static/images/categories.png"> <strong>Category:</strong> {{ club.category }}</p>
          <p><img src="/static/images/mobile.png"> <strong>Activity:</strong>{{ club.activity }}</p>
        </div>
      </li>
      {% empty %}
      <li>No clubs available.</li>
      {% endfor %}
    </ul>
    <a href="{% url 'hobby_clubs:index' %}" class="back">Back to Homepage</a>
  </div>
</body>

</html>

hobby_clubs/templates/hobby_clubs/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Turku Kids Clubs{% endblock title %}</title>
  {% block stylesheets %}{% endblock stylesheets %}
</head>

<body>


  <main>
    {% block content %}{% endblock content %}
  </main>

  {% block scripts %}{% endblock scripts %}

</body>

</html>

hobby_clubs/templates/hobby_clubs/index.html
{% extends 'hobby_clubs/base.html' %}

{% block content %}
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Website</title>
  <link rel="stylesheet" href="{% static 'homepage.css' %}">

</head>

<body>

  <header class="header">
    <img src="{% static 'images/logo3.png' %}" alt="Logo" class="logo">
    <nav>
      <ul class="navigation">
        <li><a href="{% url 'hobby_clubs:index' %}">Home</a></li>
        <li><a href="{% url 'hobby_clubs:all_clubs' %}">Clubs</a></li>
        {% if user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'hobby_clubs:user_profile' %}">Hello, {{ user.username }}</a>
          <form action="{% url 'user_accounts:logout' %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="submit" value="Log out"
              style="background: none; border: none; color: inherit; cursor: pointer; text-decoration: none;"
              class="nav-item">
          </form>
        </li>
        {% else %}
        <li><a href="{% url 'user_accounts:register' %}" class="nav-item">Register</a></li>
        <li><a href="{% url 'user_accounts:login' %}" class="nav-item">Log in</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>

  <div class="slogan">
    <h1>Find the nearest kids' clubs in Turku!</h1>
  </div>

  <div class="main-image">
    <img src="{% static 'images/homepage.jpg' %}" alt="Main Image">
  </div>

  <div class="map-image">
    <img src="{% static 'images/map.jpg' %}" alt="Map Image">

    <div class="search-info">
      <h3>Let's explore your child's interests!</h3>

      <form action="{% url 'hobby_clubs:search_clubs' %}" method="GET">
        <div class="form-group">
          <label for="postcode">Post Code: </label>
          <select id="postcode" name="postcode">

            <option selected="selected">Select Options</option>

            <option>20100</option>
            <option>20210</option>
            <option>20240</option>
            <option>20300</option>
            <option>20320</option>
            <option>20330</option>
            <option>20460</option>
            <option>20500</option>
            <option>20520</option>
            <option>20540</option>
            <option>20610</option>
            <option>20700</option>
            <option>20730</option>
            <option>20740</option>
            <option>20750</option>
            <option>20760</option>
            <option>20810</option>
            <option>20900</option>




          </select>
        </div>

        <div class="form-group">
          <label for="age">Child's Age:</label>
          <select id="age" name="age">
            <option selected="selected">Select Options</option>

            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
            <option>9</option>
            <option>10</option>
            <option>11</option>
            <option>12</option>
            <option>13</option>
            <option>14</option>


          </select>
        </div>

        <div class="form-group">
          <label for="clubtype">Club Type:</label>
          <select id="clubtype" name="clubtype">
            <option selected="selected">Select Options</option>

            <option>Sports</option>
            <option>Art</option>
            <option>Science</option>
            <option>Handcraft</option>


          </select>
        </div>
        <button type="submit" class="input-button">GET STARTED</button>
      </form>
    </div>
  </div>

  <div class="club-categories">
    <div class="club-category">
      <a href="{% url 'hobby_clubs:sports_clubs' %}"><img src="{% static 'images/sports.jpg' %}" alt="Sports"></a>
      <p><a href="{% url 'hobby_clubs:sports_clubs' %}">Sports</a></p>
    </div>
    <div class="club-category">
      <a href="{% url 'hobby_clubs:science_clubs' %}"><img src="{% static 'images/science.jpg' %}" alt="Science"></a>
      <p><a href="{% url 'hobby_clubs:science_clubs' %}">Science</a></p>
    </div>
    <div class="club-category">
      <a href="{% url 'hobby_clubs:art_clubs' %}"><img src="{% static 'images/art.jpg' %}" alt="Art"></a>
      <p><a href="{% url 'hobby_clubs:art_clubs' %}">Art</a>
      </p>
    </div>
  </div>

  <div class="social-medias">
    <div class="social-media">
      <a href="https://www.facebook.com/profile.php?id=61557054437154&is_tour_dismissed=true" target="blank"><img
          src="{% static 'images/facebook.svg' %}" alt="Facebook"></a>
    </div>
    <div class="social-media">
      <a href="https://twitter.com/TurkuClubsKids" target="blank"><img src="{% static 'images/x-twitter.svg' %}"
          alt="X"></a>
    </div>
    <div class="social-media">
      <a href="https://www.instagram.com/turkukidsclubs/" target="blank"><img src="{% static 'images/instagram.svg' %}"
          alt="Instagram"></a>
    </div>

  </div>

</body>

</html>
{% endblock content %}

hobby_clubs/templates/hobby_clubs/new_review.html
<!-- new_review.html -->

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Review</title>
</head>

<body>
  <h1>New Review - {{ club.club_name }}</h1>

  <form action="{% url 'hobby_clubs:new_review' unique_identifier=club.unique_identifier %}" method="post">
    {% csrf_token %}
    {{ review_form.as_p }}
    <button type="submit">Submit Review</button>
  </form>
</body>

</html>

hobby_clubs/templates/hobby_clubs/password_change.html
<!-- password_change.html -->

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Password Change</title>
  <link rel="stylesheet" href="{% static 'password_change.css' %}">
</head>

<body>
  <div class="password-change-container">
    <h1>Password Change</h1>
    <form method="post" action="{% url 'password_change' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change Password</button>
    </form>
  </div>
</body>

</html>

hobby_clubs/templates/hobby_clubs/search_results.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Search Results</title>
  <style>
    body {
      display: flex;
      flex-direction: column;
      align-items: center;
      background-color: #e2e0fb;
      font-family: "Comic Sans MS";
      background-image: url("/static/images/background_all.jpg");
      padding: 20px;
    }

    h1 {
      font-size: 36px;
      text-align: center;
      margin-bottom: 30px;
    }

    .home {
      font-size: 20px;
      text-decoration: none;
      float: right;
      margin-right: 20px;
      color: #d20b0b !important;
    }

    .home:hover {
      color: #984fe6 !important;
    }

    ul {
      padding: 0;
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      width: 90%;
    }

    li {
      width: 45%;
      margin-bottom: 20px;
      background-color: #d1bed1;
      border-radius: 10px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      position: relative;
      padding: 20px;
      box-sizing: border-box;
    }


    a {
      color: #007bff;
      text-decoration: none;
    }

    a:hover {
      color: #9e1344;
    }

    li img {
      width: 30px;
    }

    .apologies {
      font-size: 22px;
      color: rgb(15, 15, 14);
      text-align: center;

    }
  </style>
</head>

<body>
  <!-- <a href="{% url 'hobby_clubs:index' %}" class="home">Back to Homepage</a> -->

  <h1>Exciting Discoveries Nearby</h1>

  {% if matching_clubs %}
  <ul>
    {% for club in matching_clubs %}
    <li>
      <img src="/static/images/membership-card.png"> <strong> Club Name: </strong>{{ club.Club_Name }}<br>
      <img src="/static/images/zip-code.png"> <strong> Postal Code: </strong> {{ club.Postal_Code }}<br>
      <img src="/static/images/location-pin.png"> <strong> Address:</strong>{{ club.Address }}<br>
      <img src="/static/images/age-group.png"> <strong> Age:</strong> {{ club.Age }}<br>
      <img src="/static/images/categories.png"><strong> Category:</strong> {{ club.Category }}<br>
      <img src="/static/images/mobile.png"><strong> Activity:</strong> {{ club.Activity }}<br>
      <img src="/static/images/boost.png"><strong> Website:</strong><a href="{{ club.Website }}"> {{ club.Website }}</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p class="apologies">Apologies,</p>
  <p class="apologies"> there are currently no clubs that match your criteria.
  <p class="apologies"> Please try different search
    criteria.</p>
  {% endif %}

  <a href="{% url 'hobby_clubs:index' %}" class="home">Back to Homepage</a>

</body>

</html>